export default [
    {
        name: "Mount Aoraki",
        colors: ["purple", "blue", "yellow"],
        price: "$150",
        img: "../images/Products/shutterstock_1.jpg",
        description: "Light-weight rain jacket for long days out in the rain. Slim fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0001",
    },
    {
        name: "Mount Galdhopiggen",
        colors: ["red", "blue", "green"],
        price: "$180",
        img: "../images/Products/shutterstock_2.jpg",
        description: "A warmer rain jacket for long days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Men's",
        id: "0002",
    },
    {
        name: "Mount Bogong",
        colors: ["red", "pink", "green"],
        price: "$210",
        img: "../images/Products/shutterstock_3.jpg",
        description: "Light-weight rain jackets for long days out in the rain. Large fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0003",
    },
    {
        name: "Mount Fuji",
        colors: ["beige", "blue", "black"],
        price: "$200",
        img: "../images/Products/shutterstock_4.jpg",
        description: "A very warm rain jacket for long, cold days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Mens's",
        id: "0004",
    },
    {
        name: "Mount Roraima",
        colors: ["yellow", "pink", "green"],
        price: "$140",
        img: "../images/Products/shutterstock_5.jpg",
        description: "Light weight rain jacket for long days out in the rain. Slim fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0005",
    },
    {
        name: "Mount Karisimbi",
        colors: ["brown", "grey", "navy"],
        price: "$120",
        img: "../images/Products/shutterstock_6.jpg",
        description: "A warmer rain jacket for long, cold days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Men's",
        id: "0006",
    },
    {
        name: "Mount Elbrus",
        colors: ["purple", "blue", "yellow"],
        price: "$150",
        img: "../images/Products/shutterstock_1.jpg",
        description: "Light-weight rain jacket for long days out in the rain. Slim fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0007",
    },
    {
        name: "Mount Mercedario",
        colors: ["red", "blue", "green"],
        price: "$180",
        img: "../images/Products/shutterstock_2.jpg",
        description: "A warmer rain jacket for long days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Men's",
        id: "0008",
    },
    {
        name: "Mount Fairweather",
        colors: ["red", "pink", "green"],
        price: "$210",
        img: "../images/Products/shutterstock_3.jpg",
        description: "Light-weight rain jackets for long days out in the rain. Large fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0009",
    },
    {
        name: "Mount Meru",
        colors: ["beige", "blue", "black"],
        price: "$200",
        img: "../images/Products/shutterstock_4.jpg",
        description: "A very warm rain jacket for long, cold days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Mens's",
        id: "0010",
    },
    {
        name: "Mount Lhotse",
        colors: ["yellow", "pink", "green"],
        price: "$140",
        img: "../images/Products/shutterstock_5.jpg",
        description: "Light weight rain jacket for long days out in the rain. Slim fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Women's",
        id: "0011",
    },
    {
        name: "Mount Sinai",
        colors: ["brown", "grey", "navy"],
        price: "$120",
        img: "../images/Products/shutterstock_6.jpg",
        description: "A warmer rain jacket for long, cold days out in the rain. Normal fit",
        sizes: ["S", "M", "L", "XL", "2XL"],
        category: "Men's",
        id: "0012",
    }
]



// for (var i = 0; i < listOfJackets.length; i++) {
//     // console.log(listOfJackets[i]);
//     console.log(listOfJackets[i].sizes);
//    }